export ALLOW_MISSING_DEPENDENCIES=true
export USE_NINJA=true

add_lunch_combo aoscp_f500_usu-userdebug
add_lunch_combo aoscp_f500_usu-user
add_lunch_combo aoscp_f500_usu_eng

add_lunch_combo aoscp_h810_usu-userdebug
add_lunch_combo aoscp_h810_usu-user
add_lunch_combo aoscp_h810_usu_eng

add_lunch_combo aoscp_h811_usu-userdebug
add_lunch_combo aoscp_h811_usu-user
add_lunch_combo aoscp_h811_usu_eng

add_lunch_combo aoscp_h812_usu-userdebug
add_lunch_combo aoscp_h812_usu-user
add_lunch_combo aoscp_h812_usu_eng

add_lunch_combo aoscp_h815-userdebug
add_lunch_combo aoscp_h815-user
add_lunch_combo aoscp_h815_eng

add_lunch_combo aoscp_h815_usu-userdebug
add_lunch_combo aoscp_h815_usu-user
add_lunch_combo aoscp_h815_usu_eng

add_lunch_combo aoscp_ls991_usu-userdebug
add_lunch_combo aoscp_ls991_usu-user
add_lunch_combo aoscp_ls991_usu_eng

add_lunch_combo aoscp_us991_usu-userdebug
add_lunch_combo aoscp_us991_usu-user
add_lunch_combo aoscp_us991_usu_eng

add_lunch_combo aoscp_vs986_usu-userdebug
add_lunch_combo aoscp_vs986_usu-user
add_lunch_combo aoscp_vs986_usu_eng
