export ALLOW_MISSING_DEPENDENCIES=true
export USE_NINJA=true
export LLVM_ENABLE_THREADS=1

add_lunch_combo lineage_f500_usu-userdebug
add_lunch_combo lineage_f500_usu-user
add_lunch_combo lineage_f500_usu_eng

add_lunch_combo lineage_h810_usu-userdebug
add_lunch_combo lineage_h810_usu-user
add_lunch_combo lineage_h810_usu_eng

add_lunch_combo lineage_h811_usu-userdebug
add_lunch_combo lineage_h811_usu-user
add_lunch_combo lineage_h811_usu_eng

add_lunch_combo lineage_h812_usu-userdebug
add_lunch_combo lineage_h812_usu-user
add_lunch_combo lineage_h812_usu_eng

add_lunch_combo lineage_h815-userdebug
add_lunch_combo lineage_h815-user
add_lunch_combo lineage_h815_eng

add_lunch_combo lineage_h815_usu-userdebug
add_lunch_combo lineage_h815_usu-user
add_lunch_combo lineage_h815_usu_eng

add_lunch_combo lineage_ls991_usu-userdebug
add_lunch_combo lineage_ls991_usu-user
add_lunch_combo lineage_ls991_usu_eng

add_lunch_combo lineage_us991_usu-userdebug
add_lunch_combo lineage_us991_usu-user
add_lunch_combo lineage_us991_usu_eng

add_lunch_combo lineage_vs986_usu-userdebug
add_lunch_combo lineage_vs986_usu-user
add_lunch_combo lineage_vs986_usu_eng
